### PR TITLE
Add tender locations and addresses, make item locations and addresses plural

### LINKED ISSUE #173: Discussion: Tender location directly tied to tender
Makueni County, Kenya has tenders that are directly related to locations, regardless of the items within the tender. We are aware of the OCDS Location Extension but this assumes that items are linked to locations, which is not what we encountered. We have created an OCDS extension that depends and extends upon the OCDS Tender Location extension, but re-uses this entity directly at the tender level

https://github.com/devgateway/forms-makueni/tree/master/persistence-mongodb/src/main/resources/extensions/tender_location

### PR DESCRIPTION
**Pull request by duncandewhurst**
Closes https://github.com/open-contracting/ocds-extensions/issues/173 and https://github.com/open-contracting/ocds-extensions/issues/115

### CODE REVIEW

**Comment by duncandewhurst** [comment]
`test_json.py` reports some failures unrelated to this PR:

```
 test_json.py::test_schema_valid[/home/runner/work/ocds_location_extension/ocds_location_extension/release-schema.json-release-schema.json-data0]
  release-schema.json has "properties" within "properties" at /definitions/Location/properties/geometry

test_json.py::test_schema_valid[/home/runner/work/ocds_location_extension/ocds_location_extension/release-schema.json-release-schema.json-data0]
  release-schema.json has "properties" within "properties" at /definitions/Location/properties/gazetteer
```

and some failures relating to missing ids:

```
 test_json.py::test_json_merge_patch
  release-schema.json is missing "id" in "items/properties" at /definitions/
```

However, based on the logic in https://ocds-standard-development-handbook.readthedocs.io/en/latest/meta/schema_style_guide.html#id-field I'm not sure that an `id` field is required for addresses or locations, although we did add an `id` field to `Location` in OC4IDS.

**Comment by duncandewhurst** [comment]
@jpmckinney please can you add @odscrachel and @mrshll1001 to the team for the open-contracting-extensions organisation so that I can request a review from them?

**Comment by jpmckinney** [comment]
They have now been invited. I'll look into the tests and add exceptions as needed.

**Comment by duncandewhurst** [comment]
Thanks!

**Comment by jpmckinney** [comment]
@duncandewhurst Please set `"wholeListMerge": true` for those arrays, to make the merge behavior explicit. Feel free to add this clarification to the handbook as well.

**Review by mrshll1001 — APPROVED** [review]
All good

**Comment by yolile** [comment]
@jpmckinney I think this is ready to be merged?

**Review by jpmckinney — APPROVED** [review]

**Comment by jpmckinney** [comment]
Yes, somehow fell out of my inbox.

**Pull request merged**
